---
title: "Milestone 3"
author: "Anisha Gondesi, Mikayla Lamping, Michaela Suski"
date: "4/10/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
library(readr)
library(tidyverse)
library(patchwork)
library(tidymodels)
library(rgeos)
library(rworldmap)
library(rworldxtra)
library(tibble)
library(ggmap)
library(spData)
library(sf)
```

# What Influences the Decision to Have or Not Have Children?

## A Global Context

```{r}
mortality <- read_csv("global_mortality.csv") %>%
  filter(year == 2015) %>%
  mutate(maternal = `Maternal deaths (%)`,
         neonatal = `Neonatal deaths (%)`,
         `Maternal deaths (%)` = NULL,
         `Neonatal deaths (%)` = NULL) %>%
  select(c(country, maternal, neonatal)) %>%
  drop_na()
  
haq <- read_csv("haq_index.csv") %>%
  filter(Year == 2015) %>%
  mutate(country = Entity,
         haq = `HAQ Index (IHME (2017))`,
         Entity = NULL,
         `HAQ Index (IHME (2017))` = NULL) %>%
  select(c(country, haq))
```

```{r}
countries <- intersect(mortality$country, haq$country)
mortality <- mortality %>%
  filter(country %in% countries)
haq <- haq %>%
  filter(country %in% countries)

global_ <- inner_join(mortality, haq)
```

```{r}
wmap <- getMap(resolution="high")
centroids <- gCentroid(wmap, byid = TRUE)

locs <- as.data.frame(centroids) %>%
  rownames_to_column("country")
locs$country[236] = "United States"

global <- inner_join(global_, locs) %>%
  drop_na() %>%
  mutate(avg_mortality = rowMeans(select(., c(maternal, neonatal)), na.rm = TRUE))

world_map <- world %>%
  filter(continent != "Antarctica")
```

```{r fig.height = 8, fig.width = 15}
# map plot
ggplot() +
  geom_sf(data = world_map, fill = "white") +
  geom_point(data = global, aes(x, y, size = maternal, col = haq)) +
  scale_color_distiller(palette = "RdPu", direction = 1) +
  theme_void()
```

```{r}
high_maternal <- global %>%
  top_n(n = 10, wt = maternal)

low_maternal <- global %>%
  top_n(n = -10, wt = maternal)
```


```{r}
low <- ggplot(low_maternal) +
  geom_col(aes(maternal, reorder(country, -maternal), fill = maternal)) +
  scale_fill_distiller(palette = "RdPu", direction = 1, 
                       limits = c(min(low_maternal$maternal), max(high_maternal$maternal))) +
  ylab(label = "") +
  theme_minimal() + 
  theme(axis.text = element_text(size = 10),
        axis.title.x=element_blank(),
        panel.grid.major.y = element_blank()) +
  guides(fill="none") + 
  ggtitle("Lowest")

high <- ggplot(high_maternal) +
  geom_col(aes(maternal, reorder(country, -maternal), fill = maternal)) +
  scale_fill_distiller(palette = "RdPu", direction = 1,
                       limits = c(min(low_maternal$maternal), max(high_maternal$maternal))) +
  ylab(label = "") +
  theme_minimal() +
  theme(axis.text = element_text(size = 10),
        axis.title.x=element_blank(),
        panel.grid.major.y = element_blank()) +
  guides(fill="none") +
  ggtitle("Highest")

low + high + plot_annotation(
  title = 'Highest and Lowest Maternal Mortality Rates',
  subtitle = 'The 10 countries with the lowest and highest maternal mortality rates, respectively.',
  caption = 'Note: The x-axis scales are not the same between the two figures.'
)
```


