% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\title{Milestone 3}
\author{Anisha Gondesi, Mikayla Lamping, Michaela Suski}
\date{4/10/2022}

\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Milestone 3},
  pdfauthor={Anisha Gondesi, Mikayla Lamping, Michaela Suski},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\begin{document}
\maketitle

\hypertarget{what-influences-the-decision-to-have-or-not-have-children}{%
\section{What Influences the Decision to Have or Not Have
Children?}\label{what-influences-the-decision-to-have-or-not-have-children}}

There are many reasons why women all over the world choose not to become
pregnant and have children. Across different geographies, populations,
and cultures, these reasons may be financial, social, physical or
otherwise. This report aims to help visualize the reasons why women may
not want to have children or become pregnant.

\hypertarget{a-global-context}{%
\subsection{A Global Context}\label{a-global-context}}

Though maternal health outcomes are improving by the day, huge disparity
still exists in different areas of the world. Lower- and middle-income
countries do not have the same access to quality healthcare facilities
or medical professionals as upper-income countries. Maternal mortality
is closely linked to these factors, as demonstrated in the following
plots.

\bigskip
\bigskip

\includegraphics{Milestone3_files/figure-latex/unnamed-chunk-4-1.pdf}
\bigskip

The world map shows how countries with lower Healthcare Access and
Quality (HAQ) Indexes (represented by a lighter pink) are largely also
associated with higher maternal mortality rates (represented by larger
circles). The largest circles are also the lightest pinks, whereas the
dark pink circles are much less perceptible.

The relationship between HAQ Index and Maternal Mortality Rate is also
shown in the following scatterplot. Additionally, the relationship
between HAQ Index and Birth Attendant Skill is also explored. Birth
Attendant Skill refers to the percentage of births that were attended by
skilled medical professionals.

\includegraphics{Milestone3_files/figure-latex/unnamed-chunk-5-1.pdf}

\includegraphics{Milestone3_files/figure-latex/unnamed-chunk-6-1.pdf}

Both plots show how lower quality healthcare and limited access to it is
related to both factors influencing birth outcomes (\% skilled
attendants) as well as the outcomes themselves (maternal mortality).

These factors and outcomes are oftentimes geographically linked. The
following barplots show how countries from similar regions, like Western
Africa (Chad, Gambia, Nigeria, Senegal), are affected by a low number of
births attended by skilled personnel as well as high mortality rates.

\bigskip
\bigskip

\includegraphics{Milestone3_files/figure-latex/unnamed-chunk-8-1.pdf}

\hypertarget{social-attitudes-towards-not-having-children}{%
\subsection{Social Attitudes Towards not Having
Children}\label{social-attitudes-towards-not-having-children}}

\hypertarget{the-survey-data}{%
\subsubsection{The Survey Data}\label{the-survey-data}}

The following graphs visualize data from surveys taken in an attempt to
track societal attitudes towards having children. The survey data
included demographic information about the respondents as well as the
extent to which they agreed to various statements regarding societal
attitudes towards having children. We split the questions up by the
category of questions-Financial Factors, Societal Opinions, Outside
Influences, and Health Factors. We also visualized the survey answers by
distinguishing between both Race and Employment Status. A few things to
note about these survey results is that the survey respondents are all
women, between the ages of 17 and 63. They are all from New Jersey and
there are a mix of women who are single and/or married as well as women
with or without children. This indicates that there is a good mix of
representation from a lot of different groups of women in these survey
results.

\includegraphics{Milestone3_files/figure-latex/unnamed-chunk-12-1.pdf}
\includegraphics{Milestone3_files/figure-latex/unnamed-chunk-12-2.pdf}

From this first set of graphs, we can see that women who are African
American and Caucasian/White most strongly believe that not being in a
strong and/or stable financial situation is a large influence on whether
women decide to have a child. We can also see that women who are
employed or are students most strongly believe that not being in a
strong and/or stable financial situation influences a woman's decision
to not have a child.

\includegraphics{Milestone3_files/figure-latex/unnamed-chunk-13-1.pdf}
\includegraphics{Milestone3_files/figure-latex/unnamed-chunk-13-2.pdf}

From this set of graphs, we can see that majority of people believe that
society's opinion that woman should have children and the differences in
the way women and men are perceived when choosing not to have a child
plays a large role in an individual's decision to not have a child. On
the contrary, whether or not it is reasonable to have a child and
society's negative opinions on women who choose to have a child are both
seen as statements that do not have a large impact on an individual's
choice to have a child.

\includegraphics{Milestone3_files/figure-latex/unnamed-chunk-14-1.pdf}
\includegraphics{Milestone3_files/figure-latex/unnamed-chunk-14-2.pdf}

Two interesting observations from these graphs regarding outside
influences such as family, religion, past stories and societal pressures
are that Indians believe that social perceptions and traditions play a
large role in an individual's decision to not have a child and that
students believe that all mentioned outside influences play a large role
in an individual's decision to not have a child.

\includegraphics{Milestone3_files/figure-latex/unnamed-chunk-15-1.pdf}
\includegraphics{Milestone3_files/figure-latex/unnamed-chunk-15-2.pdf}

From these graphs, we can see that the groups that believe that health
risk factors play a large role in the decision to not have a child are
African Americans, students, and those who are employed.

Overall, there are a few notable observations and conclusions that can
be made from these visualizations. The first is that African Americans
and Caucasians/White populations as well as students and those who are
employed believe that financial factors have a large influence on an
individual's decision to not have a child. This makes sense since
African Americans and Caucasians/White populations make a large part of
the US population and for students who are possible in debt or those who
are employed and making an average salary, finances are a large factor
in deciding whether or not to have children. Another interesting
observation was that all groups felt that societal opinions played a
large role in people's decisions to have a child. These opinions
included the traditional view that it is a woman's duty to have a child
and the differences in perceptions between males and females when it
comes to choosing not to have a child. When looking at outside
influences, I found that Indians find that outside influences like
societal pressure and traditions play a large role in decision making
with having a child. This was notable since the Indian culture is known
to typically follow tradition quite a bit as well as focus a lot on
opinions of others. Another observation was that students also believed
that these outside influences play a large role in decision making when
it comes to having a child. This is also a good example of the
differences in caring about opinions between younger people and older
people. Finally, with health risks, students and those who are employed
felt that health risks are a large influence. This makes sense since
students are young and care about living a long, healthy life and those
who are employed have to focus on health insurance through their
employers. Another observation regarding health risks is that African
Americans most strongly believe that health risks influence an
individual's decision to have a child. This was something that was also
expected since historically, African Americans are treated differently
than people of other races in hospitals and typically face more health
complications due to the health care system's negligence of care for
African Americans.

The overarching conclusion made from these visualizations and
observations is that there are so many societal factors that play a role
in a person's decision on whether or not they should have a child and it
is important to consider these factors when analyzing pregnancies and
births.

\hypertarget{health-risks-associated-with-pregnancy}{%
\subsection{Health Risks Associated with
Pregnancy}\label{health-risks-associated-with-pregnancy}}

We examine how each factor is correlated in the matrix below.

\begin{verbatim}
##                     Age  SystolicBP DiastolicBP         BS    BodyTemp
## Age          1.00000000  0.41729214   0.3982341  0.4732994 -0.25663966
## SystolicBP   0.41729214  1.00000000   0.7871984  0.4254390 -0.28636626
## DiastolicBP  0.39823412  0.78719835   1.0000000  0.4238029 -0.25770201
## BS           0.47329943  0.42543897   0.4238029  1.0000000 -0.10376457
## BodyTemp    -0.25663966 -0.28636626  -0.2577020 -0.1037646  1.00000000
## HeartRate    0.06772672 -0.01832823  -0.0515417  0.1493514  0.09774947
## RiskLevel    0.26561788  0.39776788   0.3468261  0.5700965  0.16317726
##               HeartRate RiskLevel
## Age          0.06772672 0.2656179
## SystolicBP  -0.01832823 0.3977679
## DiastolicBP -0.05154170 0.3468261
## BS           0.14935140 0.5700965
## BodyTemp     0.09774947 0.1631773
## HeartRate    1.00000000 0.1903341
## RiskLevel    0.19033410 1.0000000
\end{verbatim}

Since we are exploring what may influence maternal risk levels, we
choose the three factors with the strongest relationships with risk as
indicated by the correlation matrix:blood sugar, systolic and diastolic
blood pressure, and age. We explore each of these relationships below.

To examine blood sugar values associated with the three levels of risk,
we create a box plot.

\includegraphics{Milestone3_files/figure-latex/unnamed-chunk-18-1.pdf}

\bigskip

It is clear that higher blood sugar levels are correlated with higher
pregnancy risk levels, as the high risk box plot has a much larger
average and variance. This does not necessarily indicate cause, but does
confirm the relatively large correlation value between blood sugar and
risk level (0.47329943) seen in the correlation matrix.

Next, we examine blood pressure (both Systolic and Diastolic) and risk.

\bigskip

\includegraphics{Milestone3_files/figure-latex/unnamed-chunk-19-1.pdf}

\bigskip

It is again clear that high values of these indicators correlates with
increased pregnancy risk, though this correlation appears to be slightly
weaker than blood sugar. This also confirms the direct relationship
between Systolic and Diastolic blood pressure levels predicted in the
correlation matrix (0.78719835).

Finally, we examine age.

\bigskip

\includegraphics{Milestone3_files/figure-latex/unnamed-chunk-20-1.pdf}

\bigskip

Age appears to be directly correlated with risk level. This is expected,
as it is commonly assumed that older mothers are likely to have riskier
pregnancies. There are some major outliers, however, that indicate that
age is not the sole cause of increased risk. For example, there are
several mothers over the age of 60 who are still classified as low risk.

It is important to consider how age might correlate with the other
factors recorded in this data set, as it likely influences the other
factors. In the above correlation matrix, age is positively correlated
with every factor except body temperature, which we previously found to
be of little influence on risk. Thus, age on its own may not be a cause
of higher-risk pregnancies, but rather an older age is often linked with
high values of other factors (blood sugar, blood pressure, etc.) that do
increase maternal risk.

\hypertarget{improvements-and-feedback}{%
\subsection{Improvements and Feedback}\label{improvements-and-feedback}}

Some improvements that we plan on making for our final draft would be to
make our whole report more cohesive and adding more to our analysis.
While we tried to make our graphs similar by using similar color themes,
we feel that we could do a little more to make them connect better,
which helps with the overall theme of the report as well as making the
visualizations more cohesively pleasing. We also want to improve our
analysis and work on connecting the three datasets a little more.

The specific feedback that we would like for our project is ways in
which to improve the cohesiveness of our paper and thoughts on how our
overall question/topic is being addressed. We would appreciate any
overall thoughts as well on how to improve our project, whether they be
specific to the visualizations or about our topic as a whole.

\hypertarget{references}{%
\subsection{References}\label{references}}

Mock, Thomas. (2018). Global Mortality. Retrieved March 13, 2022 from
\url{https://github.com/rfordatascience/tidytuesday/tree/master/data/2018/2018-04-16}.
\skip Our World in Data. (2015). Healthcare Access and Quality Index.
Retrieved April 10, 2022 from
\url{https://ourworldindata.org/grapher/healthcare-access-and-quality-index}.
\skip RKKaggle. (2021). Survey on Maternity(NJ, USA). Retrieved April
10, 2022 from
\url{https://www.kaggle.com/datasets/rkkaggle2/social-attitudes-regarding-childlessness-nj-survey?sel}
ect=ChildlessnessQuestions.csv \skip Safrit, Catherine. (2021,
December). Maternal Health Risk Data. Retrieved February 12, 2022 from
\url{https://www.kaggle.com/csafrit2/maternal-health-risk-data}. \skip
Zeus. (2021). World Health Statistics 2020 \textbar{} Complete
\textbar{} Geo-Analysis. Retrieved April 10, 2022 from
\url{https://www.kaggle.com/datasets/utkarshxy/who-worldhealth-statistics-2020-complete?select=nursingAndMidwife.csv}.

\end{document}
